2020-01-21 16:38:38,280 ERROR: Exception on / [GET] [in /Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/aliya/code-stuff/non-school-code/flask-tutorial/app/routes.py", line 24, in index
    return render_template('index.html', title = 'Home', posts=posts)
  File "/Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/aliya/code-stuff/non-school-code/flask-tutorial/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/aliya/code-stuff/non-school-code/flask-tutorial/app/templates/index.html", line 14, in root
    <p>{{ form.submit() }}</p>
  File "/Users/aliya/code-stuff/non-school-code/flask-tutorial/app/templates/base.html", line 54, in root
  File "/Users/aliya/code-stuff/non-school-code/flask-tutorial/app/templates/index.html", line 26, in block_content
  File "/Users/aliya/.local/share/virtualenvs/flask-tutorial-9-r7p8DH/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-01-21 16:51:31,657 INFO: Microblog startup [in /Users/aliya/code-stuff/non-school-code/flask-tutorial/app/__init__.py:44]
